"""cambiando tabla usuarioatributo contrasena por: clave  

Revision ID: e0e54e13184d
Revises: e62405185a4c
Create Date: 2025-10-15 18:33:06.601408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e0e54e13184d'
down_revision: Union[str, Sequence[str], None] = 'e62405185a4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('clave', sa.String(length=200), nullable=False))
    op.drop_column('usuario', 'contrasena')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('contrasena', mysql.VARCHAR(length=200), nullable=False))
    op.drop_column('usuario', 'clave')
    # ### end Alembic commands ###
