"""Agrego campo estado_civil a Persona

Revision ID: e62405185a4c
Revises: ee800845462c
Create Date: 2025-10-07 17:17:09.366628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e62405185a4c'
down_revision: Union[str, Sequence[str], None] = 'ee800845462c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personas', sa.Column('estado_civil', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('personas', 'estado_civil')
    # ### end Alembic commands ###
