"""Actualizo modelo Persona: agrego fecha_nacimiento y renombro columnas

Revision ID: ee800845462c
Revises: 3a08dbcde3fd
Create Date: 2025-10-07 16:35:24.868435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ee800845462c'
down_revision: Union[str, Sequence[str], None] = '3a08dbcde3fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personas', sa.Column('fecha_nacimiento', sa.Date(), nullable=False))
    op.add_column('personas', sa.Column('vivienda_propia', sa.Boolean(), nullable=True))
    op.add_column('personas', sa.Column('posee_auto', sa.Boolean(), nullable=True))
    op.drop_column('personas', 'viviendo_propia')
    op.drop_column('personas', 'posee_automotor')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personas', sa.Column('posee_automotor', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('personas', sa.Column('viviendo_propia', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('personas', 'posee_auto')
    op.drop_column('personas', 'vivienda_propia')
    op.drop_column('personas', 'fecha_nacimiento')
    # ### end Alembic commands ###
