"""create initial tables

Revision ID: f2f97751bbf2
Revises: 
Create Date: 2025-09-25 16:28:20.245942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2f97751bbf2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personas',
    sa.Column('id_persona', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('genero', sa.String(length=20), nullable=True),
    sa.Column('dni', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('fecha_registro', sa.Date(), nullable=True),
    sa.Column('contacto', sa.String(length=50), nullable=True),
    sa.Column('cantidad_hijos', sa.Integer(), nullable=True),
    sa.Column('ocupacion', sa.String(length=50), nullable=True),
    sa.Column('viviendo_propia', sa.Boolean(), nullable=True),
    sa.Column('posee_automotor', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_persona'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_personas_dni'), 'personas', ['dni'], unique=True)
    op.create_index(op.f('ix_personas_id_persona'), 'personas', ['id_persona'], unique=False)
    op.create_table('productos',
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo_producto', sa.String(length=50), nullable=True),
    sa.Column('coberturas_incluidas', sa.String(length=200), nullable=True),
    sa.Column('prima_base', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id_producto')
    )
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombre_usuario', sa.String(length=50), nullable=False),
    sa.Column('contrasena', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('rol', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nombre_usuario')
    )
    op.create_table('correo',
    sa.Column('id_correo', sa.Integer(), nullable=False),
    sa.Column('asunto', sa.String(length=200), nullable=True),
    sa.Column('cuerpo', sa.String(length=2048), nullable=True),
    sa.Column('fecha_creacion', sa.Date(), nullable=True),
    sa.Column('fecha_envio', sa.Date(), nullable=True),
    sa.Column('id_persona', sa.Integer(), nullable=True),
    sa.Column('id_producto', sa.Integer(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_persona'], ['personas.id_persona'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_correo')
    )
    op.create_table('direccion',
    sa.Column('id_direccion', sa.Integer(), nullable=False),
    sa.Column('calle', sa.String(length=100), nullable=True),
    sa.Column('numero', sa.String(length=10), nullable=True),
    sa.Column('ciudad', sa.String(length=50), nullable=True),
    sa.Column('provincia', sa.String(length=50), nullable=True),
    sa.Column('pais', sa.String(length=50), nullable=True),
    sa.Column('cod_postal', sa.String(length=20), nullable=True),
    sa.Column('id_persona', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_persona'], ['personas.id_persona'], ),
    sa.PrimaryKeyConstraint('id_direccion')
    )
    op.create_table('polizas',
    sa.Column('id_poliza', sa.Integer(), nullable=False),
    sa.Column('nro_poliza', sa.String(length=50), nullable=True),
    sa.Column('tipo_seguro', sa.String(length=50), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('suma_asegurada', sa.Float(), nullable=True),
    sa.Column('prima_pagada', sa.Float(), nullable=True),
    sa.Column('cobertura', sa.String(length=100), nullable=True),
    sa.Column('id_persona', sa.Integer(), nullable=True),
    sa.Column('id_producto', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_persona'], ['personas.id_persona'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], ),
    sa.PrimaryKeyConstraint('id_poliza'),
    sa.UniqueConstraint('nro_poliza')
    )
    op.create_table('score_event',
    sa.Column('id_score', sa.Integer(), nullable=False),
    sa.Column('puntaje', sa.Float(), nullable=True),
    sa.Column('nivel_score', sa.String(length=20), nullable=True),
    sa.Column('fecha_creacion', sa.Date(), nullable=True),
    sa.Column('id_persona', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_persona'], ['personas.id_persona'], ),
    sa.PrimaryKeyConstraint('id_score')
    )
    op.create_table('telefono',
    sa.Column('id_telefono', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('id_persona', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_persona'], ['personas.id_persona'], ),
    sa.PrimaryKeyConstraint('id_telefono')
    )
    op.create_table('pagos',
    sa.Column('id_pago', sa.Integer(), nullable=False),
    sa.Column('fecha_pago', sa.Date(), nullable=True),
    sa.Column('monto', sa.Float(), nullable=True),
    sa.Column('forma_pago', sa.String(length=50), nullable=True),
    sa.Column('estado_pago', sa.String(length=20), nullable=True),
    sa.Column('id_poliza', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_poliza'], ['polizas.id_poliza'], ),
    sa.PrimaryKeyConstraint('id_pago')
    )
    op.create_table('siniestros',
    sa.Column('id_siniestro', sa.Integer(), nullable=False),
    sa.Column('fecha_reporte', sa.Date(), nullable=True),
    sa.Column('tipo_siniestro', sa.String(length=50), nullable=True),
    sa.Column('monto_reclamado', sa.Float(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('id_poliza', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_poliza'], ['polizas.id_poliza'], ),
    sa.PrimaryKeyConstraint('id_siniestro')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('siniestros')
    op.drop_table('pagos')
    op.drop_table('telefono')
    op.drop_table('score_event')
    op.drop_table('polizas')
    op.drop_table('direccion')
    op.drop_table('correo')
    op.drop_table('usuario')
    op.drop_table('productos')
    op.drop_index(op.f('ix_personas_id_persona'), table_name='personas')
    op.drop_index(op.f('ix_personas_dni'), table_name='personas')
    op.drop_table('personas')
    # ### end Alembic commands ###
